#!/bin/sh

	#copy_location=$(adb shell ls /storage/ | dmenu -i -p "Copy Location?")
	#	if [ "$copy_location" == "emulated" ]; then
	#		copy_spot="storage/emulated/0"
	#	else
	#		copy_spot="storage/"$copy_location
	#	fi


yank_spot="$HOME/.zprivate/phone/yank/"

#pull dcim, screenshots, voice recordings, call recordings, downloads, documents
echo ""
echo "Pulling files from Device"
	adb pull /storage/62E7-3E12/DCIM/ $yank_spot
	adb pull /storage/emulated/0/DCIM/ $yank_spot
	adb pull /storage/emulated/0/Simple\ Voice\ Recorder/ $yank_spot
	adb pull /storage/emulated/0/Call\ Recorder/ $yank_spot
	adb pull /storage/emulated/0/Download/ $yank_spot
	adb pull /storage/emulated/0/Documents/ $yank_spot

echo ""
echo "Pushing files to Device"
	#copy files from
	mine_loc="$HOME/.zprivate/phone"
	music="$HOME/stuff/mu"
	#comics="$HOME/comics"
	#tvmovies="$HOME/tvmovies"

	#echo "$copy_spot"

	#will overwrite
	if [ -n "$1" ] && [ $1 == "-n" ]; then
		adb push $mine_loc/000mine/ $copy_spot
		adb push $music $copy_spot/000mine
		adb push $mine_loc/map/files $copy_spot/Android/data/net.osmand.plus/
	else
		adb push $music/rollingR/Rolling8 /storage/62E7-3E12/000mine/mu/rollingR
			#adb push rollingR/Rolling8 /storage/62E7-3E12/000mine/mu/rollingR
		adb push $music/z_akira /storage/62E7-3E12/000mine/mu/
			#adb push $HOME/stuff/mu/z_akira /storage/62E7-3E12/000mine/mu/
		adb push $mine_loc/000mine/info /storage/62E7-3E12/000mine
		adb push $mine_loc/000mine/apk /storage/62E7-3E12/000mine
	fi
	adb push $HOME/0Fork/Alon5/wg/ /storage/62E7-3E12/000mine
